{% set version = "2.0.0" %}

package:
  name: setuptools_scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-{{ version }}.tar.gz
  sha256: 638627655ec4625b7a055a5b65f44e88121fce05a281a1597abd6a9f8c04139b

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  # license_file: LICENSE
  summary: 'The blessed package to manage your versions by scm tags.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - astaric
