{% set version = "7.0.4" %}

package:
  name: setuptools_scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-{{ version }}.tar.gz
  sha256: c27bc1f48593cfc9527251f1f0fc41ce282ea57bbc7fd5a1ea3acb99325fab4c

build:
  number: 0
  noarch: python

outputs:
  - name: setuptools-scm
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - importlib-metadata
        - packaging >=20.0
        - setuptools >=45
        - tomli >=1.0.0
        - typing-extensions
    test:
      imports:
        - setuptools_scm
      commands:
        - pip check
      requires:
        - pip

  - name: setuptools_scm
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('setuptools-scm', max_pin="x.x.x") }}
    test:
      imports:
        - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  license_file: LICENSE
  summary: The blessed package to manage your versions by scm tags

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - astaric
